### ISSUE TITLE
Cannot compile on Centos 6.7

### ISSUE THREAD

**Issue by stirringhalo** [trapexit/mergerfs#150]
Hi, I have latest Centos6.7 x64. I'm using gcc-c++ 4.4.7 as installed natively from repositories.

I've had a number of compiling issues on latest 2.6.0 downloaded from https://github.com/trapexit/mergerfs/archive/2.6.0.zip, all of which I could work around:

1. add "#define UINT32_MAX  (0xffffffff)" to the top of src/config.cpp" because UINT32_MAX is not defined
2. change "fuse_bufvec    **buf," to be "struct fuse_bufvec    **buf," in both src/read_buf.hpp and src/write_buf.hpp as fuse_bufvec is not defined

But after these two issues, I ran into:

g++ -g -Wall -O2 -Wno-unused-result -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse   -DFUSE_USE_VERSION=26 -MMD -DFLAG_NOPATH=0 -DFALLOCATE=0 -DFLOCK=0 -DREAD_BUF=0 -DWRITE_BUF=0 -DUGID_USE_RWLOCK=0 -c src/ugid.cpp -o obj/ugid.o
src/ugid.cpp: In function ‘void mergerfs::ugid::initgroups(uid_t, gid_t)’:
src/ugid.cpp:77: error: ‘cache’ cannot be thread-local because it has non-POD type ‘gid_t_cache’
src/ugid.cpp:77: error: ‘cache’ is thread-local and so cannot be dynamically initialized
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-unused-result"
make: *** [obj/ugid.o] Error 1

My way around fixing this for others was to:

wget http://people.centos.org/tru/devtools-2/devtools-2.repo -O /etc/yum.repos.d/devtools-2.repo
yum install devtoolset-2-gcc devtoolset-2-binutils devtoolset-2-gcc-c++
scl enable devtoolset-2 bash
(as per http://hiltmon.com/blog/2015/08/09/c-plus-plus-11-on-centos-6-dot-6/)

With those three changes, make completes successfully.

Is it possible to patch for Centos 6.7 with the native gcc-c++?

Thanks!

P.S., thanks for writing your own union FS, I'm wary of using both mhddfs and funionfs as they are so darn old.

**Comment by stirringhalo** [comment]
I just wanted to add, same behavior on master. Last release that would compile correctly without the above changes was 2.0.1.

**Comment by trapexit** [comment]
Yeah. That's before all the recent features. The UINT issue is trivial. Unfortunately the threading issue may be harder as it's compiler and standard library related.

**Comment by stirringhalo** [comment]
Ahh, figured. Would it make sense to add to the enhanced install procedure to the README or perhaps the wiki? I'm just testing the compile now but things are looking good.

**Comment by trapexit** [comment]
I'll first try to fix it so it's more compatible. Otherwise, yes. I've debated using C++11 but for reasons like this I've not.

**Comment by stirringhalo** [comment]
Awesome. The using of devtoolset was a shot in the dark as I already had it installed for something else and was figuring GCC might've been too old. On my machine, it installs GCC 4.8.2

**Comment by stirringhalo** [comment]
Looks good! It seems to work fine in some basic mounting tests. Thanks!
